version: '3.3'
networks:
  proxy:
    external: true
services:
  app:
    container_name: app
    build: ./
    restart: always
    networks:
      - proxy
    cap_add:
      - ALL
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3
    tty: true
    stdin_open: true

  ngrok:
      image: ngrok/ngrok:3
      restart: unless-stopped
      command: 'http 3000'        
      environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      ports:
        - 4040:4040
      expose:
        - '4040'
      network_mode: 'host'